### ISSUE TITLE
Hi, PB, maybe you can add some cmake method in your tutorial

### ISSUE THREAD

**Issue by asmwarrior** [PBfordev/wxpbguide#1]
[MSYS2: using the cmake to created a wxWidgets application](https://forums.codeblocks.org/index.php/topic,24951.msg170034.html#msg170034)

Maybe, this is helpful for the beginner of wx.

**Comment by PBfordev** [comment]
Unfortunately, that would be very complicated, as the C::B wizard cannot work with CMake-built wxWidgets and I while I am familiar with the wizard code I did not find a (reasonably easy) way to implement it.

Also, building with CMake is super easy, particularly when using CMake-GUI so I believe no tutorial is needed for this. Moreover, I assume that when using CMake, one will use Code::Blocks CMake generator to create their project, not the project wizard.

**Comment by asmwarrior** [comment]
OK, I understand your statement.
