### ISSUE TITLE
Maybe use ucrt64 as the default instead of mingw64

### ISSUE THREAD

**Issue by justinmcgrath** [PBfordev/wxpbguide#3]
After using this for a while, I found a bug when using g++ in mingw64 of msys2. It doesn't print "%z" properly in `strftime`. I had to redo everything using ucrt64 instead to fix the problem.

That's a pretty narrow problem, but as I understand, the runtime that mingw64 uses is not going to be worked on, and msys recommends ucrt. Possibly ucrt64 should be what's used in the walk through, although maybe there are other reasons to favor mingw64.

Thanks for this guide nonetheless. I couldn't have gotten this working without it.

**Comment by PBfordev** [comment]
Thanks for the suggestion.

I have actually thought about switching to ucrt-based distro in the next release of the guide. At the very least, I will suggest it as the alternative to the default msvcrt one more strongly there.
