### ISSUE TITLE
Break point not working

### ISSUE THREAD

**Issue by rkamarowski** [PBfordev/wxpbguide#5]
Not sure where to post this problem, but after following your directions the code executes and presents a window, but break points are not working. Not sure what I'm doing incorrectly.
Bob K.

**Comment by PBfordev** [comment]
> Not sure where to post this problem, but after following your directions the code executes and presents a window, but break points are not working. 

Sorry, but this is obviously not an issue with my guide but with Code::Blocks. If you are sure your setup (in particular, the debugger) is correct, ask for the help on Code::Blocks forums.
